### ISSUE TITLE
Issue: Adding Location get error first

### ISSUE THREAD

**Issue by apg1980** [nerzhul/owncloud-weather#1]
...but adds location (unable to find location). After Refresh the app location appear, but only weather background image.

Server

    ownCloud version: 8.0.5
    PHP version: 5.5.25
    HTTPd server: apache 2.4.12
    HTTPS: via reverse proxy sophos utm

**Comment by nerzhul** [comment]
Can you tell me what is the string you give to application ? I need to find why

**Comment by apg1980** [comment]
i gave some german local citys like Augsburg or Königsbrunn.
First the error appears but after reload wheater information shows,

**Comment by nerzhul** [comment]
@apg1980 strange, for me this is working properly. Have you installed 1.0.2 version?
What is your browser ?
Can you look at the javascript console on your browser ?

**Comment by apg1980** [comment]
I am using 1.0.2 with ff 39.0

**Comment by nerzhul** [comment]
A login popup ? Can you look at your PHP logs / apache / owncloud/data/owncloud.log ? I think there is an error inside

**Comment by apg1980** [comment]
sorry i revert my comment accordingly to logon popup. this was a publishing rule issue.

**Comment by nerzhul** [comment]
Then, where we are ? Have you got a but or is this due to an app update ?

**Comment by nerzhul** [comment]
I updated to 1.1.0, can you update and tell me ? this is not a bugfix, but i need more informaitons

**Comment by hitam4450** [comment]
I agree to the error message !

**Comment by nerzhul** [comment]
sorry i don't understand,

**Comment by hitam4450** [comment]
Sorry, i can confirm the error message! Still have the same problem. When I press the add button a second time, it mentioned, that the city had been already added!

**Comment by nerzhul** [comment]
Okay,
can you look at firefox developper console, tab Network, then add a city and tell me what is the response (HTTP code + response message if JSON)

**Comment by hitam4450** [comment]
Sory, how to get to the developer console in FF? I do not know! I currently use FF 39!

**Comment by nerzhul** [comment]
Type F12

**Comment by hitam4450** [comment]
see screenshot
![bildschirmfoto vom 2015-07-17 10 22 56](https://cloud.githubusercontent.com/assets/9738727/8743313/dfb046b2-2c6d-11e5-88cd-e983d2525f6f.png)

**Comment by nerzhul** [comment]
409 conflict means the entry is already here. Can you add a new entry to reproduce the problem ?

**Comment by hitam4450** [comment]
The response is:
![bildschirmfoto vom 2015-07-17 10 28 18](https://cloud.githubusercontent.com/assets/9738727/8743376/9ae96b16-2c6e-11e5-8454-2abc327b7166.png)
Sorry, I have to stop now, I have to see a customer! Sorry! MAybe later!

**Comment by nerzhul** [comment]
No problem @hitam4450 thanks for your time. The message is error 500, right, i think you should look at your owncloud data/owncloud.log in the server

**Comment by nerzhul** [comment]
@hitam4450 ?

**Comment by nerzhul** [comment]
No news, closed.
