### ISSUE TITLE
Check this issue - directory name

### ISSUE THREAD

**Issue by hitam4450** [nerzhul/owncloud-weather#10]
https://github.com/owncloud/updater/issues/169

regards, hitam4450

**Comment by RealRancor** [comment]
See https://github.com/fcturner/passwords/issues/56#issuecomment-136129630 how to do this.

**Comment by nerzhul** [comment]
I do this today

**Comment by nerzhul** [comment]
Fixed on apps.owncloud.org using http://ftp.unix-experience.fr/owncloud-weather/v1.2.0.zip link with a correct archive format
