### ISSUE TITLE
NO city found

### ISSUE THREAD

**Issue by hitam4450** [nerzhul/owncloud-weather#12]
After a clean install of OC 8.2, installing and enabling the weather app I want to add a city.... I typed New York and pushed add once ...what happened ??

See enclosed screen shot!

it does not know New York, one of the most famous cities in the world!

how come ??
regards, hitam4450
![weather_1 2](https://cloud.githubusercontent.com/assets/9738727/10640454/09eb4808-7815-11e5-994c-facc36e5014d.png)

**Comment by nerzhul** [comment]
Hi @hitam4450 i look at this today, i have same problem on my instance in other paths

**Comment by nerzhul** [comment]
@hitam4450 i'm working on this. openweathermap API changed its function to add an api key, i'm currently working on it

**Comment by nerzhul** [comment]
Fixed by e863dd3dba6d0796e9cd482eaa21172cff319559
Some things are to polish and i release a new version

**Comment by lajthabalazs** [comment]
I'm now having the same issue on a freshly installed nextcloud with Weather 1.3.5

**Comment by MariusBluem** [comment]
Have you added an API key?
