### ISSUE TITLE
Missing version information for Nextcloud 11

### ISSUE THREAD

**Issue by Hanzei** [nerzhul/owncloud-weather#14]

**Comment by nerzhul** [comment]
Please add more informations, else i will close that

**Comment by Hanzei** [comment]
Server
    nextCloud version: 11.0 RC1
    PHP version: 7.0.11
After upgrading to version nextcloid 11 the warning `No lower version limit for Nextcloud was set for this app. This will be treated as an error in the future.` appeared  in the app section.

**Comment by Hanzei** [comment]
Fixed with  16c09a6
