### ISSUE TITLE
App fails to start on Nextcloud 11

### ISSUE THREAD

**Issue by Hanzei** [nerzhul/owncloud-weather#16]
**Server**
nextCloud version: 11.0 RC1
PHP version: 7.0.11

**Content of /owncloud/data/owncloud.log**
``
TypeError: Argument 5 passed to OCA\Weather\Controller\CityController::__construct() must be an instance of OCA\Weather\Controller\SettingsMapper, instance of OCA\Weather\Db\SettingsMapper given, called in /var/www/virtual/minerva/nextcloud.cjf-berlin.de/apps/weather/appinfo/application.php on line 59``
``Declaration` of OCA\Weather\Db\CityMapper::delete($id) should be compatible with OCP\AppFramework\Db\Mapper::delete(OCP\AppFramework\Db\Entity $entity) at /var/www/virtual/minerva/nextcloud.cjf-berlin.de/apps/weather/db/citymapper.php#0
``

**Comment by nerzhul** [comment]
Fixed by https://github.com/nerzhul/owncloud-weather/blob/v1.3.4/appinfo/info.xml
