### ISSUE TITLE
Set home Location

### ISSUE THREAD

**Issue by hitam4450** [nerzhul/owncloud-weather#3]
It wpould be nice to define a 'home' Location!

regards, hitam4450

**Comment by nerzhul** [comment]
Could you be more precise about HOME ? Do you mean a default weather app to select when going into app ?

**Comment by hitam4450** [comment]
I mean Home or standard wetaher location!

**Comment by nerzhul** [comment]
yes but by standard, you mean default location ?

**Comment by hitam4450** [comment]
yes.

**Comment by nerzhul** [comment]
https://github.com/nerzhul/owncloud-weather/commit/170014edabda7f064597c913ed9e8f69aa5141d9
