### ISSUE TITLE
Hovering over weather data

### ISSUE THREAD

**Issue by hitam4450** [nerzhul/owncloud-weather#4]
During hovering over weather data, they are 'blinded' by a white, solid bar!

Nothing can be seen! NO highlights!

regards, hitam4450

**Comment by nerzhul** [comment]
Right, i noticed this this morning. I will fix it today

**Comment by nerzhul** [comment]
Fixed: 5f30ba22e6f8dc0c8cdaa37f2b743d9f575c1526
