### ISSUE TITLE
Weather Theme

### ISSUE THREAD

**Issue by hitam4450** [nerzhul/owncloud-weather#5]
How about a nice Weather Theme(Background, color, style of information boxes) like the one in the screen shot??

regards, hitam4450

**Comment by nerzhul** [comment]
do you mean replacing some texts with images, for example replace sky is clear by a sun image ?

**Comment by hitam4450** [comment]
Yes, that is another idea, more pleasant then text only!

Nice Background pictureinthe app... e.g. like the one in the screenshot!

**Comment by nerzhul** [comment]
@hitam4450 thanks, i have take many time to find great illustrations for the weather with an acceptable licence :)

**Comment by hitam4450** [comment]
The sample in V 1.2 looks nicer, rather a solid dark background!

**Comment by nerzhul** [comment]
the solid dark background was due to a path problem on non root owncloud instances. Closing ticket: )
