### ISSUE TITLE
The apps disappeared

### ISSUE THREAD

**Issue by hitam4450** [nerzhul/owncloud-weather#6]
I use OC 8.1  and by checking my activated apps, i found out aboiut the new release (1.2) of the weather app.

I pressed the button to update the app.

After the app updated, it disappeared from the menu and after checking from the /apps folder as well!

Great Update!

regads, hitam4450

**Comment by nerzhul** [comment]
i think this is a problem due to the folder name. did you see owncloud-weather in your apps directory ? As i see github backend for download is not very pleasant

**Comment by hitam4450** [comment]
Well, the folder was named weather as required. However, manual update was successful. It looks much prettier now (in my opinion!)

Thanks for your efforts!
regards, hitam4450

**Comment by nerzhul** [comment]
I will modify the download to install app properly on next releases, and don't use github for this
